### ISSUE TITLE
Can't see any applications

### ISSUE THREAD

**Issue by zgr0629** [zenangst/Gray#47]
![image](https://user-images.githubusercontent.com/5328562/47208188-bb562780-d3bf-11e8-89e4-f7b07a880328.png)

Using the latest 0.9.1 version.

**Comment by zgr0629** [comment]
Gray didn't asks for Full Disk Access, I manually added Gary to have Full Disk Access, but nothing changes, still no apps in Gary.
Does anyone know the clue?

**Comment by changzhiga** [comment]
same problem, don't know how to fix this.

**Comment by zenangst** [comment]
@zgr0629 @changzhiga  version 0.9.1 had a bug when parsing applications. It should be fixed in 0.9.2 and 0.9.3.

**Comment by zgr0629** [comment]
> @zgr0629 @changzhiga version 0.9.1 had a bug when parsing applications. It should be fixed in 0.9.2 and 0.9.3.

Thanks, 0.9.3 fix this.

**Comment by zgr0629** [comment]
> @zgr0629 @changzhiga version 0.9.1 had a bug when parsing applications. It should be fixed in 0.9.2 and 0.9.3.

![menu](https://user-images.githubusercontent.com/5328562/47330020-5e9d8a00-d6a9-11e8-938e-75a0f885acf7.gif)

Hi zenangst, as this gif shows, 0.9.3 still can't show the rdm.app.

**Comment by zenangst** [comment]
What is the location of rdm.app? And what is rdm? Do you know if it is an electron based application?

**Comment by zgr0629** [comment]
> What is the location of rdm.app? And what is rdm? Do you know if it is an electron based application?

Hi zenangst, rdm.app is located at /Applications/rdm.app, as it mentioned at the top of gif. And rdm.app is an redis gui client app based on Qt 5(not an electron based application). Github page at https://github.com/uglide/RedisDesktopManager.

Dose the Qt5 application matters? I have tried to copy rdm.app to `~/Applications` and reopen Gray.app, but still can't find it.

I have found the Bundle ID of rdm.app and configures it manually in terminal:
`
mdls -name kMDItemCFBundleIdentifier /Applications/rdm.app
kMDItemCFBundleIdentifier = "com.redisdesktop.rdm"

defaults write com.redisdesktop.rdm NSRequiresAquaSystemAppearance -bool YES
`

It works, but still can't find the rdm.app in Gray.app

**Comment by zgr0629** [comment]
@zenangst Thank you, and maybe you need this script I wrote to build the latest version of rdm.app.

```bash
#!/bin/bash

SHELL_FOLDER=$(cd "$(dirname "$0")";pwd)

echo '=======================Clone RDM repository======================='
git clone --recursive https://github.com/uglide/RedisDesktopManager.git rdm
cd $SHELL_FOLDER/rdm
TAG=$(git describe --tags `git rev-list --tags --max-count=1`)

echo "=======================Switch to latest tag: ${TAG}===================="
echo 'switch to latest tag: '$TAG
cd $SHELL_FOLDER/rdm
git checkout -b $TAG $TAG

echo '=======================Build CrashReporter======================='
cd $SHELL_FOLDER/rdm/3rdparty/crashreporter
# errors on latest version of crashrepoter, build version 7ec6f00 instead.
git checkout 7ec6f00
qmake DESTDIR=./bin
make -s -j 8
mkdir -p $SHELL_FOLDER/rdm/bin/osx/release
mv $SHELL_FOLDER/rdm/3rdparty/crashreporter/bin/crashreporter $SHELL_FOLDER/rdm/bin/osx/release


echo '=======================Modify RDM version======================='
cd $SHELL_FOLDER/rdm/src
echo 'copy Info.plist'
cp resources/Info.plist.sample resources/Info.plist
echo 'modify rdm.pro'
sed -i '' "s/0.9.999/$TAG/g" rdm.pro
sed -i '' 's/debug: CONFIG-=app_bundle/#debug: CONFIG-=app_bundle/g' rdm.pro


echo "=======================Build RDM ${TAG}======================="
cd $SHELL_FOLDER/rdm/src
./configure
qmake CONFIG-=debug
make -s -j 8

echo "=======================Copy QT Framework(optional)======================="
cd $SHELL_FOLDER/rdm/bin/osx/release
macdeployqt rdm.app -qmldir=../../../src/qml

echo "=======================SUCCESS======================="
echo 'App file is:'$SHELL_FOLDER/rdm/bin/osx/release/rdm.app
```

**Comment by zenangst** [comment]
Hey @zgr0629, sorry for the delay. Can you try this new version to see if that doesn't fix your issue with `rdm.app` ?

https://github.com/zenangst/Gray/releases/download/0.9.6/Gray.zip

**Comment by zgr0629** [comment]
Hi @zenangst , I tried 0.9.6 and this version fix this bug. Thanks for the work!
